// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRAPiNT6VisJsL12vma739BB8tkwmIBcY',
    appId: '1:39865834332:web:0cbde368f6c332fd65ff99',
    messagingSenderId: '39865834332',
    projectId: 'legallywise-dddbd',
    authDomain: 'legallywise-dddbd.firebaseapp.com',
    storageBucket: 'legallywise-dddbd.appspot.com',
    measurementId: 'G-KBWRJGJMHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDJsrS8dqIjHRmyvplyxjmab6OF7J4DCI',
    appId: '1:39865834332:android:cd581e2102c0e73165ff99',
    messagingSenderId: '39865834332',
    projectId: 'legallywise-dddbd',
    storageBucket: 'legallywise-dddbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbPlVTsqJPFszWFmvEaoJirsDv5MOJHsc',
    appId: '1:39865834332:ios:135d67a9b100dce265ff99',
    messagingSenderId: '39865834332',
    projectId: 'legallywise-dddbd',
    storageBucket: 'legallywise-dddbd.appspot.com',
    iosBundleId: 'com.example.legallywise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbPlVTsqJPFszWFmvEaoJirsDv5MOJHsc',
    appId: '1:39865834332:ios:135d67a9b100dce265ff99',
    messagingSenderId: '39865834332',
    projectId: 'legallywise-dddbd',
    storageBucket: 'legallywise-dddbd.appspot.com',
    iosBundleId: 'com.example.legallywise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRAPiNT6VisJsL12vma739BB8tkwmIBcY',
    appId: '1:39865834332:web:92aee84ef7ace20f65ff99',
    messagingSenderId: '39865834332',
    projectId: 'legallywise-dddbd',
    authDomain: 'legallywise-dddbd.firebaseapp.com',
    storageBucket: 'legallywise-dddbd.appspot.com',
    measurementId: 'G-NGC4459PE7',
  );
}
